### ISSUE TITLE
Issues with proxy and Spotify?

### ISSUE THREAD

**Issue by brazilian812** [dsafa/audio-band#201]
I installed Audioband and got my developer app setup all good and have it on the taskbar and using Spotify as a source.

I am behind a proxy so I matched the proxy data in the Spotify settings with the info in the Audioband settings.

I have made sure that I have the http://localhost:80 in my Redirect URLs page, along with others varying the http(s) and other ports (8081, 8381) and set the port accordingly in Audioband

But when Spotify plays, no song info appears on Audioband.  Any ideas how to debug?  How can I check for a good port to use?  Is it something wrong with the proxy?  Not sure where to go on this

Thanks!

**Comment by brazilian812** [comment]
Ah, finally found the log file.  This is the issue.  Is it an issue with the proxy server not admitting Audioband?  Or a firewall?

2019-07-10 15:41:18.5322|ERROR|AudioSource(Spotify)|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 35.186.224.53:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadRawAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadJsonAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebAPI.<DownloadDataAsync>d__227`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<GetPlayback>d__90.MoveNext() in d:\a\1\s\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 373
---START OF EXCEPTION---

**Comment by dsafa** [comment]
Sorry about the confusion. Adding proxy settings is an old issue that I kind of forgot about #69. But since you've reminded me, I'll get an update on it.

**Comment by brazilian812** [comment]
You are dope. Thanks!

**Comment by brazilian812** [comment]
Have you been able to make progress on the proxy issue?

**Comment by dsafa** [comment]
Yep, I was relying on the spotify library to add some required proxy features and the good news is that it has since been added. I just haven't integrated the required changes yet.

**Comment by dsafa** [comment]
The previous update didn't have all the changes needed so I still need to wait for another update.
