### ISSUE TITLE
Spotify no longer working? Spotify app recently updated.

### ISSUE THREAD

**Issue by samsong** [dsafa/audio-band#283]
Spotify no longer works possibly due to spotify app or api update????
- media buttons not working: play,pause,repeat,shuffle,track progress
- media buttons working: next/prev track
-- next/prev track works
- song info/album etc do not display

Tried
- restarting windows, closing,reopening Audioband toolbar
- changing audio source from spotify to other & back to spotify
- as above, API key etc are OK because the toolbar partially works...

**Version Info**
 - Windows 10 - 21H1
 - AudioBand Version 0.9.4

Logs
`
2021-09-03 09:22:09.6523|ERROR|AudioSource(Spotify)|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'api.spotify.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadRawAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadJsonAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SpotifyAPI.Web.SpotifyWebAPI.<DownloadDataAsync>d__227`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<GetPlayback>d__91.MoveNext() in d:\a\1\s\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 434
---START OF EXCEPTION---

---END OF EXCEPTION---
---ORIGINAL EXCEPTION---
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'api.spotify.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadRawAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.SpotifyWebClient.<DownloadJsonAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SpotifyAPI.Web.SpotifyWebAPI.<DownloadDataAsync>d__227`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<GetPlayback>d__91.MoveNext() in d:\a\1\s\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 434
---END OF ORIGINAL EXCEPTION

2021-09-03 09:58:20.7550|DEBUG|AudioBand.UI.AudioBandToolbarViewModel|Deactivating current audio source "Spotify"
2021-09-03 09:58:20.7550|DEBUG|AudioBand.UI.AudioBandToolbarViewModel|Activating new audio source "Music Bee"
2021-09-03 09:58:22.5881|DEBUG|AudioBand.UI.AudioBandToolbarViewModel|Deactivating current audio source "Music Bee"
2021-09-03 09:58:22.5881|DEBUG|AudioBand.UI.AudioBandToolbarViewModel|Activating new audio source "Spotify"
2021-09-03 09:58:22.5881|DEBUG|AudioSource(Spotify)|Connecting to spotify
2021-09-03 09:58:22.5881|DEBUG|AudioSource(Spotify)|Reusing old refresh token
2021-09-03 09:58:22.5881|DEBUG|AudioSource(Spotify)|Getting new access token
2021-09-03 09:58:23.0821|DEBUG|AudioSource(Spotify)|Received new access token. Expires in: 01:00:00 (At 3/09/2021 10:58:23 am)
2021-09-03 09:59:03.4328|WARN|AudioSource(Spotify)|Error with player command [SetShuffleAsync]: Code = '404', Message = 'Player command failed: No active device found'`

**Comment by svr333** [comment]
@samsong this project is no longer maintained but [My Fork](https://github.com/svr333/audio-band) is  
Though from the stacktrace you posted it looks like you're just offline and then afterwards it connected properly but there was no device playing any music

You can try out my latest release and if the issue still persists Ill try to help you to fix it!

**Comment by samsong** [comment]
nice one man thank you I will follow & get your release
